import re
import os

# Downloader
downloader = "yt-dlp"
# Folder to download to.
folder = "C:\\SGZ_Pro\\Hobbys\\Media\\pokemon\\"

# GET THE LINKS!
# 1. Go to https://watch.pokemon.tv, select a series and do inspect element. Find the main div block, right click, press "Edit as HTML" and copy.
# 2. Paste here into the source variable making sure it starts with ''' and ends with '''. Then search to make sure player?id is in it. If there are no results, then you probably have the wrong html.

#  Pokemon Sun & Moon https://watch.pokemon.com/en-us/#/ source code with player?id links. Could expire one day :(
source = '''
<div><div class="loader-panel" style="display: none;"><div class="loader-wrapper"><div class="loader"></div></div></div> <div data-site="pcom" data-locale="en-us" data-api="https://www.pokemon.com/api/gus/" class="pokemon-gus-container">
<div class="gus-outer-container">
    <div class="gus-inner-container">
        <ul class="gus">
                <li class="gus-button pcom
                        gus-active
                    ">
                    <a href="https://www.pokemon.com/us/" class="gus-" target="_self">
                        <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/buttons/logo-pokemon-79x45.png" alt="site_slug" class="gus-bounce">
                    </a>
                </li>
                <li class="gus-button pcom
                    ">
                    <a class="gus-pokemon-center-link" target="_blank" rel="https://www.pokemoncenter.com/?utm_source=p&amp;utm_medium=referral&amp;utm_term=GUS" tabindex="0">
                        <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/buttons/logo-pokemoncenter-79x45.png" alt="site_slug" class="gus-bounce">
                    </a>
                </li>
                <li class="gus-button pcom
                    ">
                    <a href="https://www.pokemon.com/us/pokemon-tcg/play-online/" class="gus-" target="_self">
                        <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/buttons/logo-tcgo-79x45.png" alt="site_slug" class="gus-bounce">
                    </a>
                </li>
            <span class="gus-promotion-wrapper">
                    <li class="gus-promotion">
                        <a href="https://legends.pokemon.com/en-us/" class="gus-" target="_self">
                            <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/legends-arceus-176x50-us.jpg">
                        </a>
                    </li>
                    <li class="gus-promotion">
                        <a href="https://tcg.pokemon.com/en-us/" class="gus-" target="_self">
                            <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/swsh09-gus-175-en.jpg">
                        </a>
                    </li>
                    <li class="gus-promotion">
                        <a href="https://unite.pokemon.com/en-us/" class="gus-" target="_self">
                            <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/unite-176x50.jpg">
                        </a>
                    </li>
                    <li class="gus-promotion">
                        <a href="https://diamondpearl.pokemon.com/en-us/" class="gus-" target="_self">
                            <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/bd-sp-gus-175-en.jpg">
                        </a>
                    </li>
                    <li class="gus-promotion">
                        <a href="https://www.pokemon.com/us/app/" class="gus-" target="_self">
                            <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/promo-app-gallery-176x50.jpg">
                        </a>
                    </li>
            </span>
        </ul>
    </div>
</div>

<div class="gus-nav-toggle">
    <a href="#"></a>
</div>
<div class="gus-flyout-wrapper" style="z-index: 200001;">
    <div class="gus-flyout">
        <div class="gus-close">
            <a href="#"></a>
        </div>
        <div class="gus-flyout-contents">
            <ul class="gus-flyout">
                    <li class="gus-button pcom
                            gus-active
                        ">
                        <a href="https://www.pokemon.com/us/" class="gus-" target="_self">
                            <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/buttons/logo-pokemon-79x45.png" alt="site_slug" class="bounce">
                        </a>
                    </li>
                    <li class="gus-button pcom
                        ">
                        <a class="gus-pokemon-center-link" target="_blank" rel="https://www.pokemoncenter.com/?utm_source=p&amp;utm_medium=referral&amp;utm_term=GUS" tabindex="0">
                            <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/buttons/logo-pokemoncenter-79x45.png" alt="site_slug" class="bounce">
                        </a>
                    </li>
                    <li class="gus-button pcom
                        ">
                        <a href="https://www.pokemon.com/us/pokemon-tcg/play-online/" class="gus-" target="_self">
                            <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/buttons/logo-tcgo-79x45.png" alt="site_slug" class="bounce">
                        </a>
                    </li>
                <span class="gus-promotion-wrapper">
                        <li class="gus-promotion">
                            <a href="https://legends.pokemon.com/en-us/" class="gus-" target="_self">
                                <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/legends-arceus-176x50-us.jpg">
                            </a>
                        </li>
                        <li class="gus-promotion">
                            <a href="https://tcg.pokemon.com/en-us/" class="gus-" target="_self">
                                <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/swsh09-gus-175-en.jpg">
                            </a>
                        </li>
                        <li class="gus-promotion">
                            <a href="https://unite.pokemon.com/en-us/" class="gus-" target="_self">
                                <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/unite-176x50.jpg">
                            </a>
                        </li>
                        <li class="gus-promotion">
                            <a href="https://diamondpearl.pokemon.com/en-us/" class="gus-" target="_self">
                                <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/bd-sp-gus-175-en.jpg">
                            </a>
                        </li>
                        <li class="gus-promotion">
                            <a href="https://www.pokemon.com/us/app/" class="gus-" target="_self">
                                <img src="https://assets.pokemon.com/assets/cms2/img/misc/gus/promotions/promo-app-gallery-176x50.jpg">
                            </a>
                        </li>
                </span>
            </ul>
        </div>
    </div>
</div>

<div id="gus-modal" class="gus-popup" style="display:none;">
    <div class="external-link">
        <h6>You are about to leave a site operated by The Pokémon Company International, Inc.</h6>
        <p>The Pokémon Company International is not responsible for the content of any linked website that is not operated by The Pokémon Company International. Please note that these websites' privacy policies and security practices may differ from The Pokémon Company International's standards.</p>
        <div class="gus-buttons-wrapper">
            <a href="#" class="gus-button gus-button-green gus-continue-btn">
                Continue
            </a>
            <a href="#" class="gus-button gus-button-darkgray gus-close-btn">
                Cancel
            </a>
        </div>
    </div>
</div>
<div id="gus-pokemon-center-modal" class="gus-popup" style="display:none;">
    <div class="gus-external-link gus-center-link">
	    <h6>Click Continue to visit PokemonCenter.com, our official online shop.</h6>
		<h6>The privacy and security policies differ.</h6>
		<div class="gus-buttons-wrapper">
			<a href="#" class="gus-button gus-button-green gus-continue-btn">
                Continue
            </a>
			<a href="#" class="gus-button gus-button-darkgray gus-close-btn">
                Cancel
            </a>
		</div>
	</div>
</div>
<div class="gus-popup-screen" style="height: 12820px; width: 1669px;"></div></div> <header id="pokemonHeader" class="s-header sticky-top"><div class="container"><nav class="navbar nav-pills"><button name="button" class="nav-kebab btn d-block d-md-none"><div class="kebab-dot"></div> <div class="kebab-dot"></div> <div class="kebab-dot"></div></button> <a href="#/" class="nav-home-logo mr-md-3 router-link-active"><img src="/images/PTVLogo.svg" alt="Pokémon TV" class="ptv-logo"></a> <a href="#/category?id=series" class="nav-link nav-pill d-none d-md-block">
            Series
        </a> <a href="#/category?id=specials" class="nav-link nav-pill d-none d-md-block">
            Specials
        </a> <a href="#/category?id=junior" class="nav-link nav-pill d-none d-md-block">
            Junior
        </a> <a href="#/category?id=more" class="nav-link nav-pill d-none d-md-block">
            More
        </a> <button name="button" class="sign-in-button btn mr-md-auto">
                        Log In
                    </button></nav></div> <div class="c-modal" style="display: none;"><div class="modal"><div role="document" class="modal-dialog menu-modal d-flex"><div class="modal-content"><div class="modal-header"><button type="button" data-dismiss="modal" class="close p-1">
                                    ×
                                </button></div> <div class="menu-list list-group list-group-flush m-auto"><a class="menu-category list-group-item">
                                    Series
                                </a> <a class="menu-category list-group-item">
                                    Specials
                                </a> <a class="menu-category list-group-item">
                                    Junior
                                </a> <a class="menu-category list-group-item">
                                    More
                                </a></div></div></div></div></div></header> <div class="gradient-background"><div><section class="c-season-hero col-12"><div class="hero-container col-5"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/pokemon-tv-app/season20/season20-1660x940-en.png" class="hero-background" style=""> <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFcAAAAxCAQAAAAFbP2gAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQflBwgQJRltdw85AAAARElEQVRo3u3OQQ0AIAwEMMDS/GtjPyzcSFoF3bfWR046oDuHrq6urq6urq5umq6urq6urq6ubpqurq6urq6urm6aru7TlekBlGVikYAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjEtMDctMDhUMTY6Mzc6MjUrMDA6MDB0UH0/AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIxLTA3LTA4VDE2OjM3OjI1KzAwOjAwBQ3FgwAAAABJRU5ErkJggg==" class="hero-background" style="display: none;"></div> <div class="season-info-wrapper col-lg-7"><div class="bottom-season-info row col-12"><div class="row align-items-end"><h3 class="d-inline pr-2">Season 20</h3> <h6 class="d-inline">
                            43 Episodes
                        </h6></div> <div class="row"><h2>Pokémon the Series: Sun &amp; Moon</h2></div> <!----> <!----></div> <!----></div></section> <section class="c-episode-carousel c-season-episodes"><div class="row episode-card"><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=99e823676e6c4c238f9b01b42441553e&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 1
                    </p> <h4>Alola to New Adventure!</h4> <p class="episode-description-p col-12 col-md-7">What begins as a vacation for our hero on Melemele Island in the Alola region turns into the promise of many, many exciting adventures to come!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=878575d798c042b5a54a0b6c5b54b57a&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep02_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 2
                    </p> <h4>The Guardian’s Challenge!</h4> <p class="episode-description-p col-12 col-md-7">Ash and Pikachu are adjusting to life in the Alola region—and it’s about to give them a powerful push in a new direction!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=bc4f12093359420f8a0f0b5fc947fd3d&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep03_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 3
                    </p> <h4>Loading the Dex!</h4> <p class="episode-description-p col-12 col-md-7">Ash’s journey in the Alola region is just getting under way, and our hero has a new partner to share it with!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=da09d7b0d8984c43bc82ae0bf6568b4c&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep04_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 4
                    </p> <h4>First Catch in Alola, Ketchum-Style!</h4> <p class="episode-description-p col-12 col-md-7">Ash is after his first Pokémon in the Alola region, and the adventure that ensues is typical Ash!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=8f020e9c0b814c95b69152b8bb9cb22f&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep05_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 5
                    </p> <h4>Yo, Ho, Ho! Go, Popplio!</h4> <p class="episode-description-p col-12 col-md-7">Ash’s Pokémon class is off to the sea for some fishing, but Team Rocket has a completely different kind of fishing in mind!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=ad647a6bc2e64dfd916df0c62910dc55&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep06_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 6
                    </p> <h4>A Shocking Grocery Run!</h4> <p class="episode-description-p col-12 col-md-7">Ash’s first day off from Pokémon School was supposed to be a relaxing break, but things don’t go quite as expected!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=6770763773a64dc8a239eadba453b156&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep07_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 7
                    </p> <h4>That's Why the Litten Is a Scamp!</h4> <p class="episode-description-p col-12 col-md-7">A feisty Litten is determined to steal food from others, and Ash and Pikachu are determined to find out why!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=04b80411b82348079dcaf2242daeb491&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep08_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 8
                    </p> <h4>Lillie's Egg-Xhilarating Challenge!</h4> <p class="episode-description-p col-12 col-md-7">Lillie has a Pokémon Egg to care for until it hatches, but will fear get in her way?</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=26e9700f792e4d2a8f18d9007390d034&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep09_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 9
                    </p> <h4>To Top a Totem!</h4> <p class="episode-description-p col-12 col-md-7">Ash is determined to undergo the island challenge and replace his Z-Crystal, so Professor Kukui takes him to meet Hala, the kahuna of Melemele Island.</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=8eb25409a47a4feca90c3278c2530b4d&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep10_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 10
                    </p> <h4>Trial and Tribulation!</h4> <p class="episode-description-p col-12 col-md-7">The Melemele Island grand trial is imminent, and Ash must square off against the power and wisdom of Kahuna Hala!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=90ae6313ca344dd297b41680715cca95&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep11_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 11
                    </p> <h4>Young Kiawe Had a Farm!</h4> <p class="episode-description-p col-12 col-md-7">Ash has time off from school for training, but a fellow student’s activities away from school have our hero wanting to find out all about it!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=72f58050a0a449dfb9eab7c3b83fe579&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep12_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 12
                    </p> <h4>The Sun, the Scare, the Secret Lair!</h4> <p class="episode-description-p col-12 col-md-7">While our heroes enjoy a class on the beach, familiar and unfamiliar troubles are brewing behind the scenes!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=66bb36546f774eef9a0ac67a3ba2d140&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep13_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 13
                    </p> <h4>Racing to a Big Event!</h4> <p class="episode-description-p col-12 col-md-7">An Alolan tradition whets everyone’s appetite for fun, and Ash decides to join in!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=750c88587f6645d49613c1ed163509d0&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep14_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 14
                    </p> <h4>Getting to Know You!</h4> <p class="episode-description-p col-12 col-md-7">The time has come for Lillie to address her fears, and having a new friend is the perfect way to do it!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=014bc9380aa74c1ca2a4dc0025c91390&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep15_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 15
                    </p> <h4>Rocking Clawmark Hill!</h4> <p class="episode-description-p col-12 col-md-7">Rockruff’s current behavior may be a mystery, but Ash and Professor Kukui are determined to get to the bottom of it!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=b2fd56dd7c9c43d0bc6f95fd0d271d6f&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep16_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 16
                    </p> <h4>They Might Not Be Giants!</h4> <p class="episode-description-p col-12 col-md-7">Team Rocket has their eyes on our heroes’ Pokémon, but a mysterious third Pokémon has a different idea!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=bf334476108b4af8ac1ced4273240063&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep17_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 17
                    </p> <h4>Crystal-Clear Sleuthing!</h4> <p class="episode-description-p col-12 col-md-7">There’s a mystery that needs solving, and there’s also a surprising sleuth who’s determined to solve it!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=11065592af3342b69f117ad4d73a3aec&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep18_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 18
                    </p> <h4>A Seasoned Search!</h4> <p class="episode-description-p col-12 col-md-7">Rotom Dex is eager to help solve the mystery of Ash’s missing Z-Crystal!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=a848ae7a76a84d0394c24320a82c3282&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep19_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 19
                    </p> <h4>A Guardian Rematch!</h4> <p class="episode-description-p col-12 col-md-7">Ash is looking for a very important rematch, and his training regimen is breaking new ground!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=73abf965dbcd4cb998dc29959ca7ad86&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep20_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 20
                    </p> <h4>Partner Promises!</h4> <p class="episode-description-p col-12 col-md-7">A pleasant day trip for our heroes turns into an unforgettable adventure!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=9c163cb4f4194f9cbac4bf847de7e3e6&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep21_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 21
                    </p> <h4>One Journey Ends, Another Begins...</h4> <p class="episode-description-p col-12 col-md-7">The ending of one chapter in the life of a determined Pokémon ushers in the beginning of a brand-new one!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=3938627b9bf14948b9ed6a5aacab2cbd&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep22_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 22
                    </p> <h4>A Shivering Shovel Search!</h4> <p class="episode-description-p col-12 col-md-7">A day at the beach offers up our heroes much more than they bargained for!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=fc6d0e531b6a419687bb9a72bfb21b59&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep23_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 23
                    </p> <h4>Getting the Band Back Together!</h4> <p class="episode-description-p col-12 col-md-7">A major force in Alolan popular music is on the verge of collapse!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=1a1562f53eb94b198f9640702ec5bf6e&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep24_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 24
                    </p> <h4>Alolan Open House!</h4> <p class="episode-description-p col-12 col-md-7">It’s Open House day at the Pokémon School, and a surprising group of people has gathered for all the fun!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=4471f9d93bfb48dc983454a59ac9f8c5&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep25_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 25
                    </p> <h4>A Team-on-Team Tussle!</h4> <p class="episode-description-p col-12 col-md-7">There’s a Z-Crystal ripe for the picking, but are the unlikely pickers up to the task?</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=8951cccdd1c342a4875cf9a090fc2592&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep26_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 26
                    </p> <h4>So Long, Sophocles!</h4> <p class="episode-description-p col-12 col-md-7">Moving to a new place and a new life can be stressful for anyone, and the Pokémon School gang is no exception!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=4ea6b8e5eb16453ea4d91ac8e152f793&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep27_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 27
                    </p> <h4>A Glaring Rivalry!</h4> <p class="episode-description-p col-12 col-md-7">A powerful Trainer has recently appeared on Melemele Island, and Ash can’t wait to find out everything about him!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=548ca794d43a48f884268266c07f6d04&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep28_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 28
                    </p> <h4>Pulling Out the Pokémon Base Pepper!</h4> <p class="episode-description-p col-12 col-md-7">It’s Pokémon Base season in Alola, and the Pokémon School gang can’t seem to get enough of it: even playing against the enemy!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=da4ec8c7f27b48e4ae308cbaa9561dfc&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep29_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 29
                    </p> <h4>Lulled to La-La Land!</h4> <p class="episode-description-p col-12 col-md-7">A Pokémon School camping trip, complete with a scary campfire story, makes for an experience our heroes will never forget!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=afe22e30f01c41f49d4f1d9eab5cd9a4&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep30_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 30
                    </p> <h4>The Ol’ Raise and Switch!</h4> <p class="episode-description-p col-12 col-md-7">An unusual assignment at the Pokémon School gives our heroes a surprising opportunity to learn, grow, and have fun at the same time!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=0960224a28294a619ea6686741af4ec0&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep31_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 31
                    </p> <h4>The Island Whisperer!</h4> <p class="episode-description-p col-12 col-md-7">Our heroes are preparing for a field trip on Akala Island, and the island kahuna promises to make it a trip to remember!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=e6a01ab6349744178953771e8462ae6e&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep32_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 32
                    </p> <h4>Treasure Hunt, Akala Style!</h4> <p class="episode-description-p col-12 col-md-7">It’s a new day for the Pokémon School field trip, and our heroes are preparing for an adventure they will treasure forever!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=082c6b7203c74d2d90da3d82f78d09cd&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep33_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 33
                    </p> <h4>Big Sky, Small Fry!</h4> <p class="episode-description-p col-12 col-md-7">Our heroes are busy with extracurricular activities on Akala Island, and Ash and Lana are in for a great adventure!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=bcf5fabb5fdb4a44804af0f947096f03&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep34_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 34
                    </p> <h4>A Crowning Moment of Truth!</h4> <p class="episode-description-p col-12 col-md-7">The Wela Fire Festival is just starting to heat up, but someone seems determined to extinguish the celebration!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=a9857ed8addd48c2b9eb0f24028d4b29&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep35_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 35
                    </p> <h4>Currying Favor and Flavor!</h4> <p class="episode-description-p col-12 col-md-7">Our heroes are embarking on a mission filled with good taste…and a surprising finish!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=5ee56bf679d14edcb5d7a87f189df5fa&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep36_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 36
                    </p> <h4>Trials and Determinations!</h4> <p class="episode-description-p col-12 col-md-7">The time for Ash’s grand trial with Olivia is finally here, and it’s no ordinary battle!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=1a894caa2b714dc2a43091fbfa34c5eb&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep37_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 37
                    </p> <h4>Rising from the Ruins!</h4> <p class="episode-description-p col-12 col-md-7">As if Ash’s victory at his grand trial wasn’t monumental enough, an unexpected transformation makes a memorable field trip even more momentous!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=cb5e214b256e4c0590625f495605d419&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep38_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 38
                    </p> <h4>Mimikyu Unmasked!</h4> <p class="episode-description-p col-12 col-md-7">When Mimikyu faces a fashion problem, Jessie sees a bonding opportunity!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=a604c40e5beb49d3a93e23d33036ae2c&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep39_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 39
                    </p> <h4>Mallow and the Forest Teacher!</h4> <p class="episode-description-p col-12 col-md-7">It’s a challenging day for Mallow and her family restaurant, and emotions are running high!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=595d97659de54e8ea1900409a4da34af&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep40_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 40
                    </p> <h4>Balloons, Brionne, and Belligerence!</h4> <p class="episode-description-p col-12 col-md-7">Lana and Popplio are working hard to master their Z-Move, but their progress is soon to grow by leaps and bounds!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=d469ed9c5e944a61bbf406f17389e419&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep41_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 41
                    </p> <h4>Mounting an Electrifying Charge!</h4> <p class="episode-description-p col-12 col-md-7">Three of our heroes are teaming up for the annual Charjabug race, an electrifying event with shocking results!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=5be1a3e39f5544048cd3e739e69bfaf7&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep42_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 42
                    </p> <h4>Alola, Kanto!</h4> <p class="episode-description-p col-12 col-md-7">A celebratory Pokémon School class trip turns out to be a reunion no one will ever forget!</p></div> <hr class="tile-episode-divider"></div><div class="episode-thumbnail col-12"><div class="episode-img-cover col-12 col-md-4 col-lg-3"><a href="#/player?id=e0b7e7a3170e4a3e8317bbc76fc38a38&amp;channelId=pokemon-the-series-sun-moon&amp;cameFromHome=false" class="btn-play" id="play_btn_reference"><div class="episode-tile"><img src="https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season20/season20_ep43_ss01_360_206.jpg" alt="" id="img_episode_cover" style=""> <img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAABjCAQAAABHsZgxAAAAlUlEQVR42u3QMQEAAAgDIJfJ/tk0xT6IQG6HmujVqxe9evWiV69e9OrVi1696NWrF7169aJXr1706kWvXr3o1asXvXr1olevXvTqRa9evejVqxe9evWiVy969epFr1696NWrF7169aJXL3r16kWvXr3o1asXvXrRq1cvevXqRa9evejVq1evXr3o1asXvXr1olevXgoe2UB2usWr9LoAAAAASUVORK5CYII=" style="display: none;"></div> <div class="progress-bar" style="display: none;"><div class="progress-made"></div></div></a></div> <div class="tile-episode-info col-12 col-md-8 col-lg-9"><p class="tile-episode-number">
                        Episode 43
                    </p> <h4>When Regions Collide!</h4> <p class="episode-description-p col-12 col-md-7">The Cerulean Gym is the setting for old and new friends, battling old and new skills!</p></div> <hr class="tile-episode-divider"></div> <template></template> <template></template></div></section></div></div> <div class="c-modal" style="display: none;"><div class="modal"><div role="document" class="modal-dialog"><div class="modal-content"><div class="modal-body"><div class="text-container text-center"><h1></h1> <p></p> <div class="btns-container"><a type="button" class="btn btn-ok">OK</a></div></div></div></div></div></div></div> <div><div class="c-modal c-privacy-consent-modal" style="display: none;"><div class="modal"><div role="document" class="modal-dialog"><div class="modal-content"><div class="modal-body"><div class="text-container text-center mx-4"><img src="/images/PTVLogoPokemonInternational.svg" alt="" class="mb-3 pokemon-international-logo"> <h1>We value your privacy.</h1> <p>The Pokémon Company International uses analytics, diagnostics, and usage information to provide, analyze, and improve services. The Pokémon Company International collects this information anonymously.</p> <p class="mt-4">To change your usage settings, please click on Manage Usage Information. Will you agree to share your usage information?</p></div> <div class="btns-container row flex-wrap"><a type="button" class="btn btn-ok col m-3 btn-flex-center">Manage Usage Information</a> <a type="button" class="btn btn-ok col m-3 btn-flex-center">Accept</a></div></div></div></div></div></div> <div class="c-modal c-privacy-consent-modal" style="display: none;"><div class="modal"><div role="document" class="modal-dialog"><div class="modal-content"><div class="modal-body"><div class="text-container text-center mx-4"><img src="/images/PTVLogoPokemonInternational.svg" alt="" class="mb-3 pokemon-international-logo"> <p>
                    The Pokémon Company International respects your privacy. We use your usage information to help improve our services. You can allow or deny tracking of your usage information at any time.
                </p> <p class="mt-4">
                    This information will be used in accordance with the guidelines explained in the privacy notice, which you can read below.
                </p> <div class="row justify-content-center"><a type="button" target="_blank" href="https://www.pokemon.com/us/privacy-notice" class="btn">
                        Privacy Notice
                    </a></div> <hr> <div class="d-flex justify-content-between align-items-center"><h2>
                        Essential
                    </h2> <h3>
                        Always On
                    </h3></div> <p class="text-left mb-3">
                    We always collect essential information necessary to run our service and other features.
                </p> <div class="d-flex justify-content-between align-items-center"><h2>
                        Performance Cookies
                    </h2> <input id="analytics-cookies" class="blue-checkbox-input" type="checkbox"> <label for="analytics-cookies" class="blue-checkbox-label"></label></div> <p class="text-left mb-3">
                    These cookies allow us to count visits and traffic sources so we can measure and improve the performance of our site. They help us understand which pages are popular and see how visitors move around the site. All information these cookies collect is aggregated and therefore anonymous. If you do not allow these cookies, we will not know when you have visited our site, and we will not be able to monitor its performance.
                </p></div> <div class="btns-container row flex-wrap"><a type="button" class="btn btn-cancel col m-3 btn-flex-center">Cancel</a> <a type="button" class="btn btn-ok col m-3 btn-flex-center">Save My Settings</a></div></div></div></div></div></div></div> <div><footer class="s-footer"><div class="container"><div class="row"><div class="col-sm"><div class="find-social-container"><div class="social-list find"><ul class="find-social-list"><li><a target="_blank" href="https://www.facebook.com/Pokemon" class="external-link"><i class="fab fa-facebook-f"></i></a></li> <li><a target="_blank" href="https://www.twitter.com/Pokemon" class="external-link"><i class="fab fa-twitter"></i></a></li> <li><a target="_blank" href="https://www.youtube.com/channel/UCFctpiB_Hnlk3ejWfHqSm6Q" class="external-link"><i class="fab fa-youtube"></i></a></li> <li><a target="_blank" href="https://www.instagram.com/pokemon" class="external-link"><i class="fab fa-instagram"></i></a></li> <li><a target="_blank" href="https://www.pinterest.com/pokemon/" class="external-link"><i class="fab fa-pinterest-p"></i></a></li></ul></div></div></div> <div class="col-sm legal-container text-center"><h3>The Pokémon Company</h3> <a target="_blank" href="https://caru.bbbprograms.org/seal/confirmation/1596150491" class="external-link"><img src="/images/the_pokemon_company_int.png" alt=""></a> <div class="legal-links"><ul class="flex-wrap justify-content-center"><li><a href="javascript:void(0);">
                                            Manage Usage Information
                                        </a></li> <hr> <li><a target="_blank" href="https://www.pokemon.com/us/privacy-notice">Privacy Notice</a></li> <hr> <li><a target="_blank" href="https://www.pokemon.com/us/terms-of-use">Terms of Use</a></li></ul></div></div> <div class="col-sm region-container"><div class="dropdown"><button type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn btn-secondary dropdown-toggle">
                                    United States
                                </button> <div aria-labelledby="dropdownMenuButton" id="dropdownLNoptions" class="dropdown-menu"><a data-regionid="es-xl" href="/es-xl" class="dropdown-item">
            América Latina
        </a><a data-regionid="da-dk" href="/da-dk" class="dropdown-item">
            Danmark
        </a><a data-regionid="es-es" href="/es-es" class="dropdown-item">
            España
        </a><a data-regionid="fi-fi" href="/fi-fi" class="dropdown-item">
            Suomi
        </a><a data-regionid="fr-fr" href="/fr-fr" class="dropdown-item">
            France
        </a><a data-regionid="de-de" href="/de-de" class="dropdown-item">
            Deutschland
        </a><a data-regionid="it-it" href="/it-it" class="dropdown-item">
            Italia
        </a><a data-regionid="nl-nl" href="/nl-nl" class="dropdown-item">
            Nederland
        </a><a data-regionid="nb-no" href="/nb-no" class="dropdown-item">
            Norge
        </a><a data-regionid="pt-br" href="/pt-br" class="dropdown-item">
            Brasil
        </a><a data-regionid="ru-ru" href="/ru-ru" class="dropdown-item">
            Россия
        </a><a data-regionid="sv-se" href="/sv-se" class="dropdown-item">
            Sverige
        </a><a data-regionid="en-gb" href="/en-gb" class="dropdown-item">
            UK
        </a><a data-regionid="en-us" href="/en-us" class="dropdown-item">
            United States
        </a></div></div></div> <div class="col-12 legal-company"><span id="footer_copyright">©2022 Pokémon. TM, ®Nintendo.</span></div></div></div> <div class="c-modal" style="display: none;"><div class="modal"><div role="document" class="modal-dialog"><div class="modal-content"><div class="modal-body"><div class="external-link-modal"><div class="text-container"><h6>You are about to leave a site operated by The Pokémon Company International, Inc.</h6> <p>The Pokémon Company International is not responsible for the content of any linked website that is not operated by The Pokémon Company International. Please note that these websites' privacy policies and security practices may differ from The Pokémon Company International's standards.</p> <div class="btns-container row"><a type="button" class="btn btn-cancel col m-1 btn-flex-center">Cancel</a> <a type="button" class="btn btn-accept col m-1 btn-flex-center">Continue</a></div></div></div></div></div></div></div></div></footer></div></div>'''

player_id = re.findall('player\?id=.{74}',source)
for link in player_id:
    print("https://watch.pokemon.com/en-us/#/" + link.replace("&amp;","&"))
    os.system(f"cd {folder} && {downloader} https://watch.pokemon.com/en-us/#/{link.replace('&amp;','&')}")
