#+OPTIONS: toc:nil
* Python-Projects
These are small, probably not that big scripts I will use to try and learn python also try and do some small automating tasks. Bigger scripts (200 lines-/ish/) go in seperate repos.

* Directories
- =api= for testing/parsing of different API's
- =gui= for GUI (Graphical User interface) scripts
- =image= for image manipulation scripts
- =lbry= for scripts that do stuff related to the LBRY network
- =useless= for *old* scripts that don't have much usecase

Stuff that isn't inside of a directory I just haven't organized yet properly. I am trying my best not to have a thousand directorys.

* Explanations of some scripts (Outdated)
- Blog.py. A script very much for me and my setup to generate rss time to time for my blog.
- Thumbnail creator. Sometimes, I am very lazy at creating thumbnails so I decided at one point to make a basic script that just puts text on a background I created and it's kind of useful. Now a days I just cook up something in gimp as quick as possible.
- noodysee. Convert a odysee link to librarian and open in browser.
- md-to-pdf-lbry. An idea for a plugin for the fastlbry project which would convert MD to PDF with pandoc.
- mastodonrss. Get the rss link for mastodon
- lbctousd. See how much LBC is worth in USD
- file-replace. Basic program to replace a word in the file. Doesn't write the replace to the file unfortunately.
- rssgenerator. Script to print out rss links of various websites that support rss.
- rssgentk. A successor to rssgenerator which is a TK GUI application for getting rss links for various websites.

* License
These are libre scripts: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

These scripts are distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
