# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokepisode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(290, 20, 141, 31))
        self.TitleLabel.setObjectName("TitleLabel")
        self.gogoLinkButton = QtWidgets.QPushButton(self.centralwidget)
        self.gogoLinkButton.setGeometry(QtCore.QRect(60, 80, 75, 23))
        self.gogoLinkButton.setObjectName("gogoLinkButton")
        self.GoGoStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.GoGoStatusLabel.setGeometry(QtCore.QRect(10, 90, 47, 14))
        self.GoGoStatusLabel.setObjectName("GoGoStatusLabel")
        self.TorLinkButton = QtWidgets.QPushButton(self.centralwidget)
        self.TorLinkButton.setGeometry(QtCore.QRect(60, 110, 75, 23))
        self.TorLinkButton.setObjectName("TorLinkButton")
        self.TorStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.TorStatusLabel.setGeometry(QtCore.QRect(10, 110, 47, 14))
        self.TorStatusLabel.setObjectName("TorStatusLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuPokepisode = QtWidgets.QMenu(self.menubar)
        self.menuPokepisode.setObjectName("menuPokepisode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPokepisode.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TitleLabel.setText(_translate("MainWindow", "PokEpisode"))
        self.gogoLinkButton.setText(_translate("MainWindow", "GoGo"))
        self.GoGoStatusLabel.setText(_translate("MainWindow", "TextLabel"))
        self.TorLinkButton.setText(_translate("MainWindow", "Tor"))
        self.TorStatusLabel.setText(_translate("MainWindow", "TextLabel"))
        self.menuPokepisode.setTitle(_translate("MainWindow", "Pokepisode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
