#+TITLE: Leftist propaganda against guns is pure nonsense
#+OPTIONS: toc:nil num:nil 

The leftists are at it again with something semi-new *GUNS*. This comes after shootings in Buffalo and Uvalde. Some young (recently turned 18) got a gun and went to shoot a whole bunch of people. These are horrible events that cause deaths of a lot of people. But for some reason these two are the most important out of shootings that happen every single freaking week, month and most likely day.

Ok, fine but this leads to congress members trying to sign up laws to "stop" these shootings from happening. What do they propose?

- Better background checks
- 18 -> 21 age to get to get a gun
- Spend more money on mental health
- etc

I name these because I think they are there most important talking points. Let's start with the first "Better background checks", are you seriously saying that US doesn't already do this? I am pretty sure when you get a gun you also give in return all your information. So what the frick could they possibly be missing to find a possible person that's like nah we can't give you a gun because of this big red flag we see in your information. I don't understand what are they looking for. All information possible they have. If someone has mental health issues I agree they shouldn't get a gun. But it has been clarified with the uvalde shooting Salvadore had no known/documented mental issues. He still went and killed a bunch of people

The next one 18 -> 21 age to get a gun. In 3 years of this person who wants to commit a mass shooting do you really think something's going to change? Maybe that person will go get the gun illegally. 3 years doesn't change much at all in my opinion.

The last one, spend more money on mental health. What?!??@! are you saying the mental health help we currently have isn't good enouph? How do detect in the first place that someone need mental help or whatever. At less someone's parents comes banging on the phcologist door ain't nothing going to happen.

So in conclution I believe, yes we need to stop these mass shootings but not in this ANTI GUN they are evil and these terrible solution proposals.
